
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 236;
const int acc_off_y = 23;
const int acc_off_z = -238;
const float acc_scale_x = 15780.934754;
const float acc_scale_y = 16781.170740;
const float acc_scale_z = 16957.275334;

const int magn_off_x = 4;
const int magn_off_y = -170;
const int magn_off_z = -3;
const float magn_scale_x = 453.820838;
const float magn_scale_y = 472.452286;
const float magn_scale_z = 365.945257;
